function spec = paper_gain_spec(gain_id)
%PAPER_GAIN_SPEC Return the paper-era tuning definition for one scalar gain.

    gain_id = lower(string(gain_id));
    switch gain_id
        case "p_kp"
            spec = make_spec('p_kp', 'P controller', 1, 'KpP', ...
                '|K_p|', -1, 3.0, 10.^(-1:2));
        case "pi_kp"
            spec = make_spec('pi_kp', 'PI controller', 2, 'KpPI', ...
                '|K_p|', -1, 3.1, 10.^(-1:2));
        case "pi_ki"
            spec = make_spec('pi_ki', 'PI controller', 2, 'KiPI', ...
                '|K_i|', -1, 4.0, 10.^(-1:2));
        case "fuzzy_pid_kp"
            spec = make_spec('fuzzy_pid_kp', 'Fuzzy PID controller', 3, ...
                'KpCong', 'K_p', 1, 325, 10.^(0:3));
        case "fuzzy_pid_ki"
            spec = make_spec('fuzzy_pid_ki', 'Fuzzy PID controller', 3, ...
                'KiCong', 'K_i', 1, 6, 10.^(-1:2));
        case "fuzzy_pid_kd"
            spec = make_spec('fuzzy_pid_kd', 'Fuzzy PID controller', 3, ...
                'KdCong', 'K_d', 1, 6, 10.^(-1:2));
        case "fuzzy_pid_id_pair"
            spec = make_spec('fuzzy_pid_id_pair', 'Fuzzy PID controller', 3, ...
                'KiCong', 'paired K_i = K_d', 1, 6, 10.^(-1:2));
            spec.AdditionalGainVariables = {'KdCong'};
        case "fuzzy_pid_input_scale"
            spec = make_spec('fuzzy_pid_input_scale', ...
                'Fuzzy PID controller', 3, 'KinputCong', 'K_{in}', ...
                1, 1, 10.^(-1:2));
        case "proposed_kp"
            spec = make_spec('proposed_kp', 'Proposed fuzzy controller', 4, ...
                'KpProp', '|K_p|', -1, 15, 10.^(-1:2));
        case "proposed_input_scale"
            spec = make_spec('proposed_input_scale', ...
                'Proposed fuzzy controller', 4, 'KinputProp', 'K_{in}', ...
                1, 1, 10.^(-1:2));
        otherwise
            error(['Unknown gain ID "%s". Valid IDs are p_kp, pi_kp, ' ...
                'pi_ki, fuzzy_pid_kp, fuzzy_pid_ki, fuzzy_pid_kd, ' ...
                'fuzzy_pid_id_pair, fuzzy_pid_input_scale, proposed_kp, ' ...
                'and proposed_input_scale.'], gain_id);
    end
end

function spec = make_spec(id, controller_name, controller_index, ...
        gain_variable, gain_label, gain_sign, nominal_magnitude, log_magnitudes)
    spec = struct( ...
        'ID', id, ...
        'ControllerName', controller_name, ...
        'ControllerIndex', controller_index, ...
        'GainVariable', gain_variable, ...
        'AdditionalGainVariables', {{}}, ...
        'GainLabel', gain_label, ...
        'GainSign', gain_sign, ...
        'NominalMagnitude', nominal_magnitude, ...
        'LogMagnitudes', log_magnitudes);
end
